# Rails Best Practices configuration
# See http://rails-bestpractices.com/ for more information

# Exclude directories
exclude: |
  db/migrate
  db/schema.rb
  config/routes.rb
  config/initializers
  vendor
  lib/tasks
  log
  tmp
  node_modules
  app/assets/builds
  public/assets
  public/packs

# Customize rules (uncomment to enable/disable specific checks)
# RemoveDefaultScope: { }
# AddModelVirtualAttribute: { }
# AlwaysAddDbIndex: { }
# CheckSaveReturnValue: { }
# DefaultScopeIsEvil: { }
# DryBundlerInCapistrano: { }
# HashSyntax: { }
# IsolateSeedData: { }
# KeepFindersOnTheirOwnModel: { }
# LawOfDemeter: { }
# LongLine: { }
# MoveCodeIntoController: { }
# MoveCodeIntoHelper: { }
# MoveCodeIntoModel: { }
# MoveFinderToNamedScope: { }
# MoveModelLogicIntoModel: { }
# NeedlessDeepNesting: { }
# NotRescueException: { }
# NotUseDefaultRoute: { }
# NotUseTimeAgoInWords: { }
# OveruseRouteCustomizations: { }
# ProtectMassAssignment: { }
# RemoveEmptyHelpers: { }
# RemoveTrailingWhitespace: { }
# RemoveUnusedMethodsInControllers: { }
# RemoveUnusedMethodsInHelpers: { }
# RemoveUnusedMethodsInModels: { }
# ReplaceComplexCreationWithFactoryMethod: { }
# ReplaceInstanceVariableWithLocalVariable: { }
# RestrictAutoGeneratedRoutes: { }
# SimplifyRenderInControllers: { }
# SimplifyRenderInViews: { }
# UseBeforeFilter: { }
# UseModelAssociation: { }
# UseMultipartAlternativeAsContentTypeOfEmail: { }
# UseParenthesesInMethodDef: { }
# UseQueryAttribute: { }
# UseSayWithTimeInMigrations: { }
# UseScopeAccess: { }
# UseSymbolToProc: { }
# UseTimeZone: { }

